project:
  type: website

website:
  title: "Testing Web-Pages"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    - text: Lectures
      menu:
      - href: lectures/week1-intro/test-md.qmd
        text: Week 1 - Intro
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
