project:
  type: website

website:
  title: "Testing Web-Pages"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    - text: Lectures
      menu:
      - href: lectures/week1-intro/test-md.qmd
        text: Week 1 - Intro
      - href: lectures/week13-random-slope/Week13-Longitudinal-Part-1-rev1.qmd
        text: Week 13 - Random Slope
      - href: lectures/week13-random-slope/Week13-Random-Intercept-Slope-Example.qmd
        text: Week 13 - Random Intercept Slope

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
